// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjgZuAU6k9vo67AUs397RUjPeBNIkJnvo',
    appId: '1:804195865130:web:d9b2e8022bd944d2eba953',
    messagingSenderId: '804195865130',
    projectId: 'real-estate-app-4d9f1',
    authDomain: 'real-estate-app-4d9f1.firebaseapp.com',
    storageBucket: 'real-estate-app-4d9f1.firebasestorage.app',
    measurementId: 'G-HRVCNX11VK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTcRE291mku-z6DBC54yHsYW6Ji0r15d8',
    appId: '1:804195865130:android:227c6c8ff40489a0eba953',
    messagingSenderId: '804195865130',
    projectId: 'real-estate-app-4d9f1',
    storageBucket: 'real-estate-app-4d9f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwArtvRDeZIAE06e0AP4-6OeJKm_R10Jc',
    appId: '1:804195865130:ios:b13f8482267779c3eba953',
    messagingSenderId: '804195865130',
    projectId: 'real-estate-app-4d9f1',
    storageBucket: 'real-estate-app-4d9f1.firebasestorage.app',
    androidClientId: '804195865130-e2iiftqaho4l62jtjq8v9hoa9fd4n2ud.apps.googleusercontent.com',
    iosClientId: '804195865130-53ahs646jjrve3c2g6vbvpf1g9pofo6q.apps.googleusercontent.com',
    iosBundleId: 'com.example.p2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwArtvRDeZIAE06e0AP4-6OeJKm_R10Jc',
    appId: '1:804195865130:ios:b13f8482267779c3eba953',
    messagingSenderId: '804195865130',
    projectId: 'real-estate-app-4d9f1',
    storageBucket: 'real-estate-app-4d9f1.firebasestorage.app',
    androidClientId: '804195865130-e2iiftqaho4l62jtjq8v9hoa9fd4n2ud.apps.googleusercontent.com',
    iosClientId: '804195865130-53ahs646jjrve3c2g6vbvpf1g9pofo6q.apps.googleusercontent.com',
    iosBundleId: 'com.example.p2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjgZuAU6k9vo67AUs397RUjPeBNIkJnvo',
    appId: '1:804195865130:web:b07628e8fcf66b57eba953',
    messagingSenderId: '804195865130',
    projectId: 'real-estate-app-4d9f1',
    authDomain: 'real-estate-app-4d9f1.firebaseapp.com',
    storageBucket: 'real-estate-app-4d9f1.firebasestorage.app',
    measurementId: 'G-W44CLCTLNW',
  );
}
